### ISSUE TITLE
re-consider `data-*` prefix [decided]

### ISSUE THREAD

**Issue by tgaff** [SF-WDI-LABS/angular_style_guide#7]
re-consider https://github.com/SF-WDI-LABS/angular_style_guide#prefix-data--on-attributes-and-directives

This rule is not recommended by ToddMotto or JohnPapa's guides.  It also is just extra typing for us since we've never used a validator and would likely have to add exceptions if we used element directives anyway.

**Comment by nathanallen** [comment]
Group Decision: Intro/mention `data-*` but use `ng-shorthand` for convenience instead of `data-ng-longhand`
